In [1]:
import numpy as np

In [9]:
emp = np.empty((3,4), dtype = int)
print(emp)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
fp = np.full((3,4),7)
print(fp)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [14]:
ze = np.zeros(5, dtype=int)
print(ze)
on = np.ones(4)
print(on,"\n")
ze = np.zeros([5,4], dtype=int)
print(ze,"\n")
on = np.ones([4,2])
print(on)


[0 0 0 0 0]
[1. 1. 1. 1.] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
nz = eval(input("Enter a list: "))
print("Your list is: ",nz)
uniq, count = np.unique(nz,return_counts=True)
for i in range(len(uniq)):
    print(uniq[i], "    ", count[i])

Your list is:  [12, 3, 5, 6, 7, 7, 6, 45]
3      1
5      1
6      2
7      2
12      1
45      1


In [35]:
nar = [1,4,3,2,5,74,8,0]
print(nar)
nar.sort()
p=nar[::-1]
print(p)

[1, 4, 3, 2, 5, 74, 8, 0]
[74, 8, 5, 4, 3, 2, 1, 0]


In [46]:
#i = int(input("Enter binary number: "))
i = 1001011
ll = np.zeros(50)
while(i):
    np.insert(ll,1,5)
    i = i/10
print(ll)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
