In [2]:
import numpy as np

In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
for i in Z:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
for i in Z:
    for j in i:
        print(j, end = "  ")
    print(" ")

0  1  2   
3  4  5   
6  7  8   


In [ ]:
print(np.__version__)

1.16.2


In [ ]:
print(type(Z))

<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [ ]:
print(Z.dtype)

int32


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [ ]:
t = np.arange(1,11,2)
p = t.copy()
print("p= ",p)
print("t= ",t)
p[3] = 8
t[2] = 6
print("p= ",p)
print("t= ",t)
print(p.base)

p=  [1 3 5 7 9]
t=  [1 3 5 7 9]
p=  [1 3 5 8 9]
t=  [1 3 6 7 9]
None


In [ ]:
p = t.view()
print("p= ",p)
print("t= ",t)
p[3] = 8
t[2] = 6
print("p= ",p)
print("t= ",t)

p=  [1 3 6 7 9]
t=  [1 3 6 7 9]
p=  [1 3 6 8 9]
t=  [1 3 6 8 9]


In [ ]:
print(p.base)

[1 3 6 8 9]


In [ ]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
Z = np.eye(4)
print(2*Z)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


In [ ]:
Z = np.random.random((2,2))
print(Z*100)
print("Minimum: ", int(Z.min()*100))
print("Maximum: ", int(Z.max()*100))

[[1.94995127 1.39855631]
 [0.65622945 1.48231539]]
Minimum:  32
Maximum:  97


In [ ]:
o = np.arange(12,33)
print(o.mean())

22.0


In [ ]:
Z = np.zeros((5,5)).astype('i')
Z[1:-1, 1:-1] = 1
print(Z.dtype)
print(Z)

int32
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
